# Generated by Django 5.0.6 on 2024-06-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vitornet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts2',
            new_name='Post',
        ),
    ]
