# Generated by Django 5.0.6 on 2024-06-24 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitornet_app', '0005_alter_like_post_alter_like_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank='True', null=True, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
